version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: | 
          commit_message=$(git log -1 HEAD --pretty=format:%b)
          if ! [[ $commit_message == *"[ci build]"* ]]; then
            echo $CIRCLE_WORKFLOW_ID
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/job/$CIRCLE_JOB/cancel \
            --header "Circle-Token: ${CIRCLE_TOKEN}"
            circleci step halt
          fi
          echo $commit_message
      - run: echo "1111"
