version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: | 
          commit_message=$(git log -1 HEAD --pretty=format:%b)
          if ! [[ $commit_message == *"[ci build]"* ]]; then
            echo $CIRCLE_WORKFLOW_ID
            curl --request POST \
            --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
            --header "Circle-Token: ${CIRCLE_TOKEN}"
          fi
      - run: echo "1111"
  job1:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "1"
  job2:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "1"
      
workflows:
   build_ios:
     jobs:
       - build
       - hold:
           type: approval
           requires:
             - build
       - job2:
           requires:
             - hold
