version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      #- run: git log $CIRCLE_SHA1 | grep '[ci build]'
      #- run: git log -1 HEAD --pretty=format:%s | grep "[ci build]"
      #- run: git log -1 HEAD --grep="[ci build"]
      #- run: git log -1 HEAD | grep "[dsfsdf44"]
      #- run: git log -1 HEAD --pretty=format:'%b'
      #- run: git show -s --format=%B $CIRCLE_SHA1 | grep '[ci build]' | echo
      #- run: git show -s --format=%B $CIRCLE_SHA1
     # - run: git log -1 --pretty=%B
- run: | 
    commit_message=$(git log -1 HEAD --pretty=format:%s)
    if [[ $commit_message == *"[ci build]"* ]]; then
      echo 'found
    fi
