version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      #- run: git log $CIRCLE_SHA1 | grep '[ci build]'
      #- run: git log -1 HEAD --pretty=format:%s | grep "[ci build]"
      #- run: git log -1 HEAD --grep="[ci build"]
      #- run: git log -1 HEAD | grep "[dsfsdf44"]
      #- run: git log -1 HEAD --pretty=format:'%b'
      - run: git show -s --format=%B $CIRCLE_SHA1 | grep '\[ci' | echo
     # - run: git log -1 --pretty=%B
