version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: | 
          commit_message=$(git log -1 HEAD --pretty=format:%b)
          if ! [[ $commit_message == *"[ci build]"* ]]; then
            curl --request POST \
            --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
            --header "Circle-Token: ${CIRCLE_TOKEN}"
          fi
          echo $commit_message
