version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: | 
          commit_message=$(git log -1 HEAD --pretty=format:%b)
          if ! [[ $commit_message == *"[ci build]"* ]]; then
            exit 1
          fi
          echo $commit_message 
      - run: | 
          echo 'export COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%b)' >> $BASH_ENV
      - run: echo $COMMIT_MESSAGE
      - run: echo 'step 3'
 
