version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      #- run: git log $CIRCLE_SHA1 | grep '[ci build]'
      - run: git log -1 HEAD --pretty=format:%s
